# netlify.toml
[build]
  base    = "frontend" # Diz ao Netlify para entrar na pasta 'frontend' primeiro
  publish = "frontend/dist" # A pasta que o Netlify deve servir ao público
  command = "npm install && npm run build" # Comandos para construir o projeto

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
